"""baseline - full schema as of 2026-04-18

Revision ID: 13091cc0ca0a
Revises: 
Create Date: 2026-04-18 08:37:20.413413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13091cc0ca0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_flags_key')

    with op.batch_alter_table('key_rotation_history', schema=None) as batch_op:
        batch_op.drop_index('ix_key_rotation_created_at')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('key_rotation_history', schema=None) as batch_op:
        batch_op.create_index('ix_key_rotation_created_at', ['created_at'], unique=False)

    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index('ix_feature_flags_key', ['flag_key'], unique=1)

    # ### end Alembic commands ###
