"""EmailDraft — per-recipient personalized email content, generated by LLM
before send. Lives between Campaign creation and the Sender Agent: users
can review, edit, and regenerate individual drafts before final batch send.

Why this exists:
- Plain Jinja2 template rendering only personalizes 4 placeholder fields
  (name/platform/followers/industry) — that's "salutation-level", not
  "content-level" personalization. BD outreach needs the latter.
- Generating LLM content live in the Sender Agent (no review step) is
  unsafe — LLMs can hallucinate facts about an influencer. Drafts give
  the user a review/edit gate.
- Storing drafts in a dedicated table (vs polluting the Templates table)
  keeps the "reusable template library" semantics clean. Templates are
  abstract masters; drafts are concrete per-influencer instances.
"""
import enum
from datetime import datetime

from sqlalchemy import (
    String,
    Text,
    Enum,
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.database import Base


class EmailDraftStatus(str, enum.Enum):
    pending = "pending"          # queued for LLM generation
    generating = "generating"    # LLM in flight
    ready = "ready"              # generation succeeded; awaiting user review
    edited = "edited"            # user edited (excluded from bulk regenerate)
    failed = "failed"            # LLM failed (user can manually regenerate)
    sending = "sending"          # sender agent picked it up
    sent = "sent"                # email sent (terminal)
    cancelled = "cancelled"      # user removed before send


class EmailDraft(Base):
    __tablename__ = "email_drafts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)

    campaign_id: Mapped[int] = mapped_column(
        ForeignKey("campaigns.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    influencer_id: Mapped[int] = mapped_column(
        ForeignKey("influencers.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    template_id: Mapped[int | None] = mapped_column(
        ForeignKey("templates.id", ondelete="SET NULL"),
        nullable=True,
    )

    # Rendered content. Empty strings allowed during pending / generating.
    subject: Mapped[str] = mapped_column(String(512), nullable=False, default="")
    body_html: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Generation metadata for telemetry / re-cache / A-B variant tracking.
    angle_used: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generation_model: Mapped[str | None] = mapped_column(String(64), nullable=True)
    generation_prompt_hash: Mapped[str | None] = mapped_column(
        String(64), nullable=True, index=True,
    )

    status: Mapped[EmailDraftStatus] = mapped_column(
        Enum(EmailDraftStatus),
        default=EmailDraftStatus.pending,
        nullable=False,
        index=True,
    )
    # User-edited drafts are protected from bulk-regenerate operations.
    edited_by_user: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Forward link to the Email record once sent — supports audit trail
    # ("which draft generated this email?"). SET NULL on email delete so
    # purging old emails doesn't cascade-delete drafts.
    email_id: Mapped[int | None] = mapped_column(
        ForeignKey("emails.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    generated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    __table_args__ = (
        # One draft per (campaign, influencer) — re-running generate replaces.
        UniqueConstraint(
            "campaign_id", "influencer_id",
            name="uq_email_drafts_campaign_influencer",
        ),
        Index("ix_email_drafts_campaign_status", "campaign_id", "status"),
    )
