"""
Admin Follow-up API — global strategy config + Responder audit + emergency controls.
"""
from typing import Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field
from sqlalchemy import func, select

from app.api.admin.deps import require_admin
from app.database import AsyncSessionLocal
from app.models.email import Email, EmailType
from app.models.influencer import Influencer
from app.schemas.auth import TokenData
from app.services.follow_up_service import get_or_create_settings, update_settings

router = APIRouter(prefix="/followup", tags=["admin-followup"])


# ─── Schemas ──────────────────────────────────────────────────────────────────

class FollowUpSettingsOut(BaseModel):
    id: int
    enabled: bool
    interval_days: int
    max_count: int
    hour_utc: int
    created_at: str
    updated_at: str


class FollowUpSettingsPatch(BaseModel):
    enabled: Optional[bool] = None
    interval_days: Optional[int] = Field(None, ge=1, le=365)
    max_count: Optional[int] = Field(None, ge=1, le=50)
    hour_utc: Optional[int] = Field(None, ge=0, le=23)


class ResponderLogItem(BaseModel):
    email_id: int
    influencer_id: int
    influencer_name: Optional[str]
    influencer_email: str
    influencer_platform: Optional[str]
    original_reply: Optional[str]
    reply_from: Optional[str]
    follow_up_subject: str
    follow_up_status: str
    sent_at: Optional[str]
    replied_at: Optional[str]
    created_at: str


# ─── Settings ─────────────────────────────────────────────────────────────────

@router.get("/settings", response_model=FollowUpSettingsOut)
async def get_settings(_: TokenData = Depends(require_admin)) -> FollowUpSettingsOut:
    async with AsyncSessionLocal() as db:
        s = await get_or_create_settings(db)
        return FollowUpSettingsOut(
            id=s.id,
            enabled=s.enabled,
            interval_days=s.interval_days,
            max_count=s.max_count,
            hour_utc=s.hour_utc,
            created_at=s.created_at.isoformat(),
            updated_at=s.updated_at.isoformat(),
        )


@router.patch("/settings", response_model=FollowUpSettingsOut)
async def patch_settings(
    body: FollowUpSettingsPatch,
    _: TokenData = Depends(require_admin),
) -> FollowUpSettingsOut:
    async with AsyncSessionLocal() as db:
        s = await update_settings(
            db,
            enabled=body.enabled,
            interval_days=body.interval_days,
            max_count=body.max_count,
            hour_utc=body.hour_utc,
        )
        return FollowUpSettingsOut(
            id=s.id,
            enabled=s.enabled,
            interval_days=s.interval_days,
            max_count=s.max_count,
            hour_utc=s.hour_utc,
            created_at=s.created_at.isoformat(),
            updated_at=s.updated_at.isoformat(),
        )


# ─── Emergency Controls ────────────────────────────────────────────────────────

@router.post("/pause-all")
async def pause_all(_: TokenData = Depends(require_admin)) -> dict:
    async with AsyncSessionLocal() as db:
        await update_settings(db, enabled=False)
    return {"ok": True, "message": "All follow-ups paused"}


@router.post("/resume-all")
async def resume_all(_: TokenData = Depends(require_admin)) -> dict:
    async with AsyncSessionLocal() as db:
        await update_settings(db, enabled=True)
    return {"ok": True, "message": "All follow-ups resumed"}


# ─── Responder Logs ────────────────────────────────────────────────────────────

@router.get("/responder-logs")
async def get_responder_logs(
    page: int = 1,
    page_size: int = 20,
    _: TokenData = Depends(require_admin),
) -> dict:
    """
    Return follow-up emails that were generated by the Responder Agent,
    showing the original reply → the generated follow-up email.
    """
    async with AsyncSessionLocal() as db:
        base_q = (
            select(Email, Influencer)
            .join(Influencer, Email.influencer_id == Influencer.id)
            .where(Email.email_type == EmailType.follow_up)
            .order_by(Email.created_at.desc())
        )
        total = (await db.execute(
            select(func.count()).select_from(
                select(Email.id)
                .where(Email.email_type == EmailType.follow_up)
                .subquery()
            )
        )).scalar_one()

        offset = (page - 1) * page_size
        rows = (await db.execute(base_q.offset(offset).limit(page_size))).all()

        items = []
        for email, inf in rows:
            items.append(ResponderLogItem(
                email_id=email.id,
                influencer_id=inf.id,
                influencer_name=inf.nickname,
                influencer_email=inf.email,
                influencer_platform=inf.platform.value if inf.platform else None,
                original_reply=email.reply_content,
                reply_from=email.reply_from,
                follow_up_subject=email.subject,
                follow_up_status=email.status.value,
                sent_at=email.sent_at.isoformat() if email.sent_at else None,
                replied_at=email.replied_at.isoformat() if email.replied_at else None,
                created_at=email.created_at.isoformat(),
            ))

        return {"items": items, "total": total, "page": page, "page_size": page_size}
